Android.bp: build libdrm shared for host
Required to fix following mesa build errors:

error: external/mesa/src/mesa/Android.bp:29:1: dependency "libdrm" of "libmesa_glsl_utils" missing variant:
  os:linux_glibc, arch:x86_64, link:shared
...
error: external/mesa/src/mesa/Android.bp:49:1: dependency "libdrm" of "mesa_gen_matypes" missing variant:
  os:linux_glibc, arch:x86, link:shared

Change-Id: Iaf3ff2a8672d4cfc73eee18b01b56d70f314a6d0