libsync.h: fix missing braces in (struct sync_merge_data) data
Fixes the following build error in IA-HardwareComposer when using clang:

In file included from external/IA-Hardware-Composer/common/core/hwclayer.cpp:18:
external/libdrm/libsync.h:88:33:
error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        struct sync_merge_data data = {0};
                                       ^
                                       {}

Using -Wno-missing-braces in external/IA-Hardware-Composer/common/core/Android.mk
LOCAL_CPPFLAGS did not solve the issue, this change in external/libdrm/libsync.h
was necessary

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>